package main

import (
	"errors"
	"fmt"
	"io"
	"strings"
)

type completionCommand struct {
	Name        string
	Description string
	Flags       []string
	Args        string
	Subcommands []completionCommand
}

var runnerLifecycleFlags = []string{"--workspace", "--workdir", "--current", "--all", "-w", "-d"}

var completionCommands = []completionCommand{
	{Name: "list", Description: "List configured runners", Flags: runnerLifecycleFlags},
	{Name: "launch", Description: "Launch configured runners", Flags: runnerLifecycleFlags},
	{Name: "park", Description: "Park running runners", Flags: runnerLifecycleFlags},
	{Name: "restart", Description: "Restart running runners", Flags: runnerLifecycleFlags},
	{Name: "remove", Description: "Retain configured runners and fail closed", Flags: runnerLifecycleFlags},
	{Name: "doctor", Description: "Diagnose runner state", Flags: runnerLifecycleFlags},
	{Name: "reconcile", Description: "Reconcile runner state", Flags: runnerLifecycleFlags},
	{Name: "runner", Description: "Manage machine-local workdir-bound runners", Subcommands: []completionCommand{
		{Name: "maintenance", Description: "Manage scheduled runner maintenance", Subcommands: []completionCommand{
			{Name: "install", Description: "Install scheduled maintenance", Flags: []string{"--update-owner"}},
			{Name: "remove", Description: "Remove scheduled maintenance"},
			{Name: "run", Description: "Run maintenance", Flags: []string{"--scheduled"}},
		}},
		{Name: "list", Description: "List configured runners", Flags: runnerLifecycleFlags},
		{Name: "pin", Description: "Pin a runner", Flags: []string{"--workspace", "--workdir", "--current", "-w", "-d"}},
		{Name: "unpin", Description: "Remove an absent runner's exact registry binding", Flags: []string{"--workdir", "--current", "-d"}},
		{Name: "teardown", Description: "Stop one exact runner, remove its Git worktree, and unpin it", Flags: []string{"--workdir", "--confirm-plan", "-d"}},
		{Name: "launch", Description: "Launch runners", Flags: runnerLifecycleFlags},
		{Name: "park", Description: "Park runners", Flags: runnerLifecycleFlags},
		{Name: "restart", Description: "Restart runners", Flags: runnerLifecycleFlags},
		{Name: "remove", Description: "Retain configured runners and fail closed", Flags: runnerLifecycleFlags},
		{Name: "doctor", Description: "Diagnose runners", Flags: runnerLifecycleFlags},
		{Name: "reconcile", Description: "Reconcile runners", Flags: runnerLifecycleFlags},
	}},
	{Name: "workspace", Description: "Inspect configured runner workspaces", Subcommands: []completionCommand{
		{Name: "list", Description: "List runner workspaces"},
	}},
	{Name: "workspaces", Description: "Exact alias for workspace list"},
	{Name: "install", Description: "Inspect the amux client installation", Subcommands: []completionCommand{
		{Name: "doctor", Description: "Diagnose executable targets, versions, and PATH drift"},
	}},
	{Name: "migrate-config", Description: "Copy the legacy runner registry into ~/.config/amux"},
	{Name: "completion", Description: "Print shell completion script", Args: "<bash|zsh|fish>"},
	{Name: "update", Description: "Update a user-local amux release install"},
	{Name: "version", Description: "Print version and build metadata"},
	{Name: "path", Description: "Print the config directory"},
	{Name: "help", Description: "Print help"},
}

var globalCompletionFlags = []string{"--config-dir", "--json", "--dry-run", "--attach", "--no-attach", "--terminal-launcher", "--help", "-h", "--version", "-c", "-j", "-n"}

func (a app) completion(args []string) error {
	if len(args) != 1 {
		return errors.New("usage: amux completion <bash|zsh|fish>")
	}
	switch args[0] {
	case "bash":
		writeBashCompletion(a.stdout)
	case "zsh":
		writeZshCompletion(a.stdout)
	case "fish":
		writeFishCompletion(a.stdout)
	default:
		return fmt.Errorf("unsupported shell %q; expected bash, zsh, or fish", args[0])
	}
	return nil
}

func writeBashCompletion(w io.Writer) {
	fmt.Fprintf(w, `# bash completion for amux; generated by amux completion bash
_amux_complete() {
  local cur command leaf branch i word
  cur="${COMP_WORDS[COMP_CWORD]}"
  for ((i=1; i<COMP_CWORD; i++)); do
    word="${COMP_WORDS[i]}"
    if [[ "$word" == --config-dir || "$word" == -c || "$word" == --terminal-launcher ]]; then ((i++)); continue; fi
    if [[ "$word" == --config-dir=* || "$word" == -c=* || "$word" == --terminal-launcher=* || "$word" == --json || "$word" == -j || "$word" == --dry-run || "$word" == -n || "$word" == --attach || "$word" == --no-attach || "$word" == --help || "$word" == -h || "$word" == --version ]]; then continue; fi
    if [[ -z "$command" ]]; then command="$word"
    elif [[ ( "$command" == runner || "$command" == workspace || "$command" == install ) && -z "$leaf" ]]; then leaf="$word"
    elif [[ "$command" == runner && "$leaf" == maintenance && -z "$branch" ]]; then branch="$word"
    fi
  done
  if [[ -z "$command" ]]; then COMPREPLY=( $(compgen -W "%s %s" -- "$cur") ); return; fi
  case "$command" in
    runner)
      if [[ -z "$leaf" ]]; then COMPREPLY=( $(compgen -W "%s" -- "$cur") )
      elif [[ "$leaf" == maintenance && -z "$branch" ]]; then COMPREPLY=( $(compgen -W "%s" -- "$cur") )
      elif [[ "$leaf" == maintenance && "$branch" == install ]]; then COMPREPLY=( $(compgen -W "--update-owner" -- "$cur") )
      elif [[ "$leaf" == maintenance && "$branch" == run ]]; then COMPREPLY=( $(compgen -W "--scheduled" -- "$cur") )
      elif [[ "$leaf" == maintenance ]]; then COMPREPLY=()
      elif [[ "$leaf" == pin ]]; then COMPREPLY=( $(compgen -W "--workspace --workdir --current -w -d" -- "$cur") )
      elif [[ "$leaf" == unpin ]]; then COMPREPLY=( $(compgen -W "--workdir --current -d" -- "$cur") )
      elif [[ "$leaf" == teardown ]]; then COMPREPLY=( $(compgen -W "--workdir --confirm-plan -d" -- "$cur") )
      else COMPREPLY=( $(compgen -W "--workspace --workdir --current --all -w -d" -- "$cur") ); fi ;;
    workspace) if [[ -z "$leaf" ]]; then COMPREPLY=( $(compgen -W "list" -- "$cur") ); fi ;;
    install) if [[ -z "$leaf" ]]; then COMPREPLY=( $(compgen -W "doctor" -- "$cur") ); fi ;;
    completion) COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;
    list|launch|park|restart|remove|doctor|reconcile) COMPREPLY=( $(compgen -W "--workspace --workdir --current --all -w -d" -- "$cur") ) ;;
  esac
}
complete -F _amux_complete amux
`, strings.Join(commandNames(completionCommands), " "), strings.Join(globalCompletionFlags, " "), strings.Join(commandNames(runnerCompletionCommands()), " "), strings.Join(commandNames(runnerMaintenanceCompletionCommands()), " "))
}

func writeZshCompletion(w io.Writer) {
	fmt.Fprint(w, "#compdef amux\n# zsh completion for amux; generated by amux completion zsh\n\n")
	fmt.Fprintln(w, "local context state line command leaf branch word\nlocal -i i\nlocal -a commands runner_commands maintenance_commands")
	fmt.Fprintln(w, "commands=(")
	for _, command := range completionCommands {
		fmt.Fprintf(w, "  %q\n", command.Name+":"+command.Description)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w, "runner_commands=(")
	for _, command := range runnerCompletionCommands() {
		fmt.Fprintf(w, "  %q\n", command.Name+":"+command.Description)
	}
	fmt.Fprintln(w, ")\nmaintenance_commands=(")
	for _, command := range runnerMaintenanceCompletionCommands() {
		fmt.Fprintf(w, "  %q\n", command.Name+":"+command.Description)
	}
	fmt.Fprintln(w, `)
for ((i=2; i<CURRENT; i++)); do
  word=$words[i]
  if [[ $word == --config-dir || $word == -c || $word == --terminal-launcher ]]; then ((i++)); continue; fi
  if [[ $word == --config-dir=* || $word == -c=* || $word == --terminal-launcher=* || $word == --json || $word == -j || $word == --dry-run || $word == -n || $word == --attach || $word == --no-attach || $word == --help || $word == -h || $word == --version ]]; then continue; fi
  if [[ -z $command ]]; then command=$word
  elif [[ ( $command == runner || $command == workspace || $command == install ) && -z $leaf ]]; then leaf=$word
  elif [[ $command == runner && $leaf == maintenance && -z $branch ]]; then branch=$word
  fi
done
_arguments -C \
  '(-c --config-dir)'{-c,--config-dir}'[select config directory]:directory:_directories' \
  '(-j --json)'{-j,--json}'[emit JSON]' '(-n --dry-run)'{-n,--dry-run}'[plan only]' \
  '--attach[attach after launch]' '--no-attach[never attach]' \
  '--terminal-launcher=[terminal launcher command]:command:' \
  '1:command:->command' '*::argument:->args'
case $state in
  command) _describe -t commands 'amux command' commands ;;
  args)
    case $command in
      runner)
        if [[ -z $leaf ]]; then _describe -t commands 'runner command' runner_commands
        elif [[ $leaf == maintenance && -z $branch ]]; then _describe -t commands 'maintenance command' maintenance_commands
        elif [[ $leaf == maintenance && $branch == install ]]; then _arguments '--update-owner=[update owner]:owner:(self external)'
        elif [[ $leaf == maintenance && $branch == run ]]; then _arguments '--scheduled[scheduled invocation]'
        elif [[ $leaf == maintenance ]]; then return
        elif [[ $leaf == pin ]]; then _arguments '(-w --workspace)'{-w,--workspace}'[workspace]:name:' '(-d --workdir)'{-d,--workdir}'[workdir]:directory:_directories' '--current[current workdir]'
        elif [[ $leaf == unpin ]]; then _arguments '(-d --workdir)'{-d,--workdir}'[workdir]:directory:_directories' '--current[current workdir]'
        elif [[ $leaf == teardown ]]; then _arguments '(-d --workdir)'{-d,--workdir}'[workdir]:directory:_directories' '--confirm-plan=[fresh teardown plan digest]:sha256:'
        else _arguments '(-w --workspace)'{-w,--workspace}'[workspace]:name:' '(-d --workdir)'{-d,--workdir}'[workdir]:directory:_directories' '--current[current workdir]' '--all[all runners]'; fi ;;
      workspace) _values 'workspace command' list ;;
      install) _values 'install command' doctor ;;
      completion) _values 'shell' bash zsh fish ;;
      list|launch|park|restart|remove|doctor|reconcile) _arguments '(-w --workspace)'{-w,--workspace}'[workspace]:name:' '(-d --workdir)'{-d,--workdir}'[workdir]:directory:_directories' '--current[current workdir]' '--all[all runners]' ;;
    esac ;;
esac`)
}

func writeFishCompletion(w io.Writer) {
	fmt.Fprintln(w, "# fish completion for amux; generated by amux completion fish")
	for _, flag := range []struct{ short, long, description string }{
		{"c", "config-dir", "Select config directory"}, {"j", "json", "Emit JSON"}, {"n", "dry-run", "Plan only"},
		{"", "attach", "Attach after launch"}, {"", "no-attach", "Never attach"}, {"", "terminal-launcher", "Terminal launcher command"},
	} {
		short := ""
		if flag.short != "" {
			short = " -s " + flag.short
		}
		requiresValue := ""
		if flag.long == "config-dir" || flag.long == "terminal-launcher" {
			requiresValue = " -r"
		}
		fmt.Fprintf(w, "complete -c amux%s -l %s%s -d %s\n", short, flag.long, requiresValue, fishQuote(flag.description))
	}
	for _, command := range completionCommands {
		fmt.Fprintf(w, "complete -c amux -n '__fish_use_subcommand' -a %s -d %s\n", fishQuote(command.Name), fishQuote(command.Description))
	}
	for _, command := range runnerCompletionCommands() {
		fmt.Fprintf(w, "complete -c amux -n '__fish_seen_subcommand_from runner; and not __fish_seen_subcommand_from %s' -a %s -d %s\n", strings.Join(commandNames(runnerCompletionCommands()), " "), fishQuote(command.Name), fishQuote(command.Description))
	}
	for _, command := range runnerMaintenanceCompletionCommands() {
		fmt.Fprintf(w, "complete -c amux -n '__fish_seen_subcommand_from maintenance; and not __fish_seen_subcommand_from install remove run' -a %s -d %s\n", fishQuote(command.Name), fishQuote(command.Description))
	}
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from workspace; and not __fish_seen_subcommand_from list' -a list -d 'List runner workspaces'")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from install; and not __fish_seen_subcommand_from doctor' -a doctor -d 'Diagnose installation'")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from list launch park restart remove doctor reconcile pin; and not __fish_seen_subcommand_from maintenance' -l workspace -s w -r")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from list launch park restart remove doctor reconcile pin unpin teardown; and not __fish_seen_subcommand_from maintenance' -l workdir -s d -r")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from list launch park restart remove doctor reconcile; and not __fish_seen_subcommand_from maintenance' -l all")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from list launch park restart remove doctor reconcile pin unpin; and not __fish_seen_subcommand_from maintenance' -l current")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from teardown; and not __fish_seen_subcommand_from maintenance' -l confirm-plan -r")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from maintenance; and __fish_seen_subcommand_from install' -l update-owner -r -a 'self external'")
	fmt.Fprintln(w, "complete -c amux -n '__fish_seen_subcommand_from maintenance; and __fish_seen_subcommand_from run' -l scheduled")
}

func commandNames(commands []completionCommand) []string {
	names := make([]string, 0, len(commands))
	for _, command := range commands {
		names = append(names, command.Name)
	}
	return names
}

func runnerCompletionCommands() []completionCommand { return completionSubcommands("runner") }

func runnerMaintenanceCompletionCommands() []completionCommand {
	for _, command := range runnerCompletionCommands() {
		if command.Name == "maintenance" {
			return command.Subcommands
		}
	}
	return nil
}

func workspaceCompletionCommands() []completionCommand { return completionSubcommands("workspace") }

func completionSubcommands(name string) []completionCommand {
	for _, command := range completionCommands {
		if command.Name == name {
			return command.Subcommands
		}
	}
	return nil
}

func fishFlagNames(flag string) (short, long string) {
	if strings.HasPrefix(flag, "--") {
		return "", strings.TrimPrefix(flag, "--")
	}
	if strings.HasPrefix(flag, "-") {
		return strings.TrimPrefix(flag, "-"), ""
	}
	return "", ""
}

func fishQuote(value string) string { return "'" + strings.ReplaceAll(value, "'", "\\'") + "'" }
