package main

import (
	"errors"
	"fmt"
	"io"
	"strings"
)

type completionCommand struct {
	Name        string
	Description string
	Flags       []string
	Args        string
	Subcommands []completionCommand
}

var completionCommands = []completionCommand{
	{Name: "launch", Description: "Launch or attach a tmux session", Args: "[workspace] [session]"},
	{Name: "list", Description: "Print configured restore rows", Flags: []string{"--status", "--active", "--shelved"}, Args: "[workspace]"},
	{Name: "workspaces", Description: "Print configured workspace names", Flags: []string{"--include-runners"}},
	{Name: "shelved", Description: "Shortcut for list --shelved", Args: "[workspace]"},
	{Name: "pin", Description: "Add or replace one restore row", Args: "<workspace> <window> <workdir> <thread-id-or-url>"},
	{Name: "store", Description: "Alias for pin", Args: "<workspace> <window> <workdir> <thread-id-or-url>"},
	{Name: "pin-current", Description: "Pin the current tmux window", Args: "<thread-id-or-url> | <workspace> <thread-id-or-url> [window] [workdir]"},
	{Name: "store-current", Description: "Alias for pin-current", Args: "<thread-id-or-url> | <workspace> <thread-id-or-url> [window] [workdir]"},
	{Name: "unpin", Description: "Remove one restore row", Args: "<workspace> <window>"},
	{Name: "remove", Description: "Alias for unpin", Args: "<workspace> <window>"},
	{Name: "unpin-current", Description: "Remove the current tmux window from restore config", Args: "[workspace]"},
	{Name: "remove-current", Description: "Alias for unpin-current", Args: "[workspace]"},
	{Name: "park", Description: "Stop a live local tmux window without changing restore config", Args: "[workspace] <window>"},
	{Name: "park-current", Description: "Stop the current tmux window without changing restore config", Args: "[workspace]"},
	{Name: "shelve-current", Description: "Pin if needed, archive the thread, and stop the current window", Args: "[workspace] [thread-id-or-url]"},
	{Name: "shelve", Description: "Archive thread rows while preserving restore config", Flags: []string{"--thread", "--workspace", "--session"}, Args: "[workspace] <window> [session]"},
	{Name: "unshelve", Description: "Unarchive shelved thread rows", Flags: []string{"--thread", "--workspace"}, Args: "[workspace] <window>"},
	{Name: "spawn", Description: "Create a new Amp thread in a tmux window", Flags: []string{"--mode", "-m", "--title-prefix", "--message-file", "--message-stdin"}, Args: "<window> <workdir> [initial-message] [workspace] [session]"},
	{Name: "teardown", Description: "Archive a thread, remove its row, and stop its window", Flags: []string{"--thread", "--session"}, Args: "[workspace] <window> [session]"},
	{Name: "prune-archived", Description: "Remove restore rows whose threads are archived", Args: "[workspace]"},
	{Name: "migrate-config", Description: "Copy legacy config files into ~/.config/amux"},
	{
		Name:        "runner",
		Description: "Manage amp --no-tui runner rows",
		Subcommands: []completionCommand{
			{Name: "list", Description: "Print configured runner rows", Args: "[workspace]"},
			{Name: "pin", Description: "Add or replace one runner row", Args: "<workspace> <window> <workdir>"},
			{Name: "unpin", Description: "Remove one runner row", Args: "<workspace> <window>"},
			{Name: "launch", Description: "Start configured runner windows", Args: "[workspace] [session]"},
			{Name: "park", Description: "Stop a live local runner window", Args: "[workspace] <window>"},
		},
	},
	{Name: "completion", Description: "Print shell completion script", Args: "<bash|zsh|fish>"},
	{Name: "update", Description: "Update a user-local amux release install"},
	{Name: "self-update", Description: "Alias for update"},
	{Name: "version", Description: "Print version and build metadata"},
	{Name: "path", Description: "Print the config path"},
	{Name: "doctor", Description: "Check dependencies, config, and live tmux drift", Args: "[workspace] [session]"},
	{Name: "help", Description: "Print help"},
}

var globalCompletionFlags = []string{"--config", "--dry-run", "--attach", "--no-attach", "--terminal-launcher", "--help", "-h", "--version"}

func (a app) completion(args []string) error {
	if len(args) != 1 {
		return errors.New("usage: amux completion <bash|zsh|fish>")
	}
	switch args[0] {
	case "bash":
		writeBashCompletion(a.stdout)
	case "zsh":
		writeZshCompletion(a.stdout)
	case "fish":
		writeFishCompletion(a.stdout)
	default:
		return fmt.Errorf("unsupported shell %q; expected bash, zsh, or fish", args[0])
	}
	return nil
}

func writeBashCompletion(w io.Writer) {
	fmt.Fprintf(w, `# bash completion for amux; generated by amux completion bash
_amux_complete() {
  local cur prev command subcommand word i skip_next
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  case "$prev" in
    --config|--message-file)
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
    --terminal-launcher|--mode|-m|--title-prefix|--thread|--workspace|--session)
      return 0
      ;;
  esac

  skip_next=0
  for ((i = 1; i < COMP_CWORD; i++)); do
    word="${COMP_WORDS[i]}"
    if (( skip_next )); then
      skip_next=0
      continue
    fi
    case "$word" in
      --config|--terminal-launcher|--mode|-m|--title-prefix|--message-file|--thread|--workspace|--session)
        skip_next=1
        continue
        ;;
      --config=*|--terminal-launcher=*|--mode=*|--title-prefix=*|--message-file=*|--thread=*|--workspace=*|--session=*|--dry-run|--attach|--no-attach|--status|--active|--shelved|--include-runners|--message-stdin|--help|-h|--version)
        continue
        ;;
    esac
    if [[ -z "$command" ]]; then
      command="$word"
      continue
    fi
    if [[ "$command" == "runner" && -z "$subcommand" ]]; then
      subcommand="$word"
      continue
    fi
  done

  if [[ -z "$command" ]]; then
    COMPREPLY=( $(compgen -W "%s %s" -- "$cur") )
    return 0
  fi

  case "$command" in
    list)
      COMPREPLY=( $(compgen -W "--status --active --shelved" -- "$cur") )
      ;;
    workspaces)
      COMPREPLY=( $(compgen -W "--include-runners" -- "$cur") )
      ;;
    shelve)
      COMPREPLY=( $(compgen -W "--thread --workspace --session" -- "$cur") )
      ;;
    unshelve)
      COMPREPLY=( $(compgen -W "--thread --workspace" -- "$cur") )
      ;;
    spawn)
      COMPREPLY=( $(compgen -W "--mode -m --title-prefix --message-file --message-stdin" -- "$cur") )
      ;;
    teardown)
      COMPREPLY=( $(compgen -W "--thread --session" -- "$cur") )
      ;;
    runner)
      if [[ -z "$subcommand" ]]; then
        COMPREPLY=( $(compgen -W "list pin unpin launch park" -- "$cur") )
      fi
      ;;
    completion)
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
      ;;
  esac
}
complete -F _amux_complete amux
`, strings.Join(commandNames(completionCommands), " "), strings.Join(globalCompletionFlags, " "))
}

func writeZshCompletion(w io.Writer) {
	fmt.Fprintln(w, "#compdef amux")
	fmt.Fprintln(w, "# zsh completion for amux; generated by amux completion zsh")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "local -a commands")
	fmt.Fprintln(w, "commands=(")
	for _, command := range completionCommands {
		fmt.Fprintf(w, "  %q\n", command.Name+":"+command.Description)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "local -a runner_commands")
	fmt.Fprintln(w, "runner_commands=(")
	for _, command := range runnerCompletionCommands() {
		fmt.Fprintf(w, "  %q\n", command.Name+":"+command.Description)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w)
	fmt.Fprintln(w, `_arguments -C \
  '--config[path to restore config]:config file:_files' \
  '--dry-run[print intended actions without mutating]' \
  '--attach[always attach after launch]' \
  '--no-attach[never attach after launch]' \
  '--terminal-launcher[terminal launcher command]:command:' \
  '--help[print help]' \
  '-h[print help]' \
  '--version[print version]' \
  '1:command:->command' \
  '*::arg:->args'

case $state in
  command)
    _describe -t commands 'amux command' commands
    ;;
  args)
    case $words[2] in
      list)
        _arguments '--status[append thread status]' '--active[only confirmed active rows]' '--shelved[only confirmed shelved rows]' '*:workspace:'
        ;;
      workspaces)
        _arguments '--include-runners[include runner-only workspaces]'
        ;;
      shelve)
        _arguments '--thread[select by thread id or URL]:thread:' '--workspace[select all rows in workspace]:workspace:' '--session[tmux session]:session:' '*:arg:'
        ;;
      unshelve)
        _arguments '--thread[select by thread id or URL]:thread:' '--workspace[select all rows in workspace]:workspace:' '*:arg:'
        ;;
      spawn)
        _arguments '--mode[thread mode]:mode:' '-m[thread mode]:mode:' '--title-prefix[window/thread title prefix]:prefix:' '--message-file[read initial message from file]:message file:_files' '--message-stdin[read initial message from stdin]' '*:arg:'
        ;;
      teardown)
        _arguments '--thread[select by thread id or URL]:thread:' '--session[tmux session]:session:' '*:arg:'
        ;;
      runner)
        if (( CURRENT == 3 )); then
          _describe -t runner-commands 'runner command' runner_commands
        fi
        ;;
      completion)
        _values 'shell' bash zsh fish
        ;;
    esac
    ;;
esac`)
}

func writeFishCompletion(w io.Writer) {
	fmt.Fprintln(w, "# fish completion for amux; generated by amux completion fish")
	for _, flag := range globalCompletionFlags {
		writeFishFlag(w, "__fish_use_subcommand", flag, flagDescription(flag), flagTakesValue(flag))
	}
	for _, command := range completionCommands {
		fmt.Fprintf(w, "complete -c amux -f -n '__fish_use_subcommand' -a %s -d %s\n", fishQuote(command.Name), fishQuote(command.Description))
	}
	for _, command := range completionCommands {
		condition := fmt.Sprintf("__fish_seen_subcommand_from %s", command.Name)
		for _, flag := range command.Flags {
			writeFishFlag(w, condition, flag, flagDescription(flag), flagTakesValue(flag))
		}
		if command.Name == "runner" {
			for _, subcommand := range command.Subcommands {
				fmt.Fprintf(w, "complete -c amux -f -n '__fish_seen_subcommand_from runner; and not __fish_seen_subcommand_from %s' -a %s -d %s\n", strings.Join(commandNames(command.Subcommands), " "), fishQuote(subcommand.Name), fishQuote(subcommand.Description))
			}
		}
		if command.Name == "completion" {
			fmt.Fprintln(w, "complete -c amux -f -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'")
		}
	}
}

func writeFishFlag(w io.Writer, condition, flag, description string, takesValue bool) {
	short, long := fishFlagNames(flag)
	parts := []string{"complete", "-c", "amux", "-n", fishQuote(condition)}
	if takesValue {
		parts = append(parts, "-r")
	} else {
		parts = append(parts, "-f")
	}
	if short != "" {
		parts = append(parts, "-s", fishQuote(short))
	}
	if long != "" {
		parts = append(parts, "-l", fishQuote(long))
	}
	parts = append(parts, "-d", fishQuote(description))
	fmt.Fprintln(w, strings.Join(parts, " "))
}

func commandNames(commands []completionCommand) []string {
	names := make([]string, 0, len(commands))
	for _, command := range commands {
		names = append(names, command.Name)
	}
	return names
}

func runnerCompletionCommands() []completionCommand {
	for _, command := range completionCommands {
		if command.Name == "runner" {
			return command.Subcommands
		}
	}
	return nil
}

func flagDescription(flag string) string {
	switch flag {
	case "--config":
		return "Path to restore config"
	case "--dry-run":
		return "Print intended actions without mutating"
	case "--attach":
		return "Always attach after launch"
	case "--no-attach":
		return "Never attach after launch"
	case "--terminal-launcher":
		return "Terminal launcher command"
	case "--status":
		return "Append thread status"
	case "--active":
		return "Only confirmed active rows"
	case "--shelved":
		return "Only confirmed shelved rows"
	case "--thread":
		return "Select by thread id or URL"
	case "--workspace":
		return "Select workspace rows"
	case "--session":
		return "Tmux session"
	case "--mode", "-m":
		return "Amp thread mode"
	case "--title-prefix":
		return "Window and thread title prefix"
	case "--message-file":
		return "Read initial message from file"
	case "--message-stdin":
		return "Read initial message from stdin"
	case "--include-runners":
		return "Include runner-only workspaces"
	case "--help", "-h":
		return "Print help"
	case "--version":
		return "Print version"
	default:
		return flag
	}
}

func flagTakesValue(flag string) bool {
	switch flag {
	case "--config", "--terminal-launcher", "--thread", "--workspace", "--session", "--mode", "-m", "--title-prefix", "--message-file":
		return true
	default:
		return false
	}
}

func fishFlagNames(flag string) (short, long string) {
	if strings.HasPrefix(flag, "--") {
		return "", strings.TrimPrefix(flag, "--")
	}
	if strings.HasPrefix(flag, "-") {
		return strings.TrimPrefix(flag, "-"), ""
	}
	return "", flag
}

func fishQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
