package main

import (
	"errors"
	"fmt"
	"io"
	"strings"
)

type completionCommand struct {
	Name        string
	Description string
	Flags       []string
	Args        string
	Subcommands []completionCommand
}

var completionCommands = []completionCommand{
	{
		Name:        "worker",
		Description: "Manage interactive thread-bound clients",
		Subcommands: []completionCommand{
			{Name: "list", Description: "List configured workers", Flags: []string{"--workspace", "--thread", "--shelf", "--current", "--all"}},
			{Name: "pin", Description: "Pin a worker", Flags: []string{"--workspace", "--window", "--workdir", "--thread", "--current"}},
			{Name: "unpin", Description: "Unpin a worker", Flags: []string{"--thread", "--current"}},
			{Name: "launch", Description: "Launch workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "park", Description: "Park workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "restart", Description: "Restart workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "remove", Description: "Remove workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "spawn", Description: "Spawn a worker", Flags: []string{"--workspace", "--window", "--workdir", "--mode", "-m", "--message", "--message-file", "--message-stdin", "--idempotency-key"}},
			{Name: "shelve", Description: "Shelve workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "unshelve", Description: "Unshelve workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "teardown", Description: "Teardown workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "doctor", Description: "Diagnose workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
			{Name: "reconcile", Description: "Reconcile workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
		},
	},
	{Name: "spawn", Description: "Spawn a worker", Flags: []string{"--workspace", "--window", "--workdir", "--mode", "-m", "--message", "--message-file", "--message-stdin", "--idempotency-key"}},
	{Name: "shelve", Description: "Shelve workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
	{Name: "unshelve", Description: "Unshelve workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
	{Name: "teardown", Description: "Teardown workers", Flags: []string{"--workspace", "--thread", "--current", "--all"}},
	{Name: "migrate-config", Description: "Copy legacy config files into ~/.config/amux"},
	{Name: "completion", Description: "Print shell completion script", Args: "<bash|zsh|fish>"},
	{Name: "update", Description: "Update a user-local amux release install"},
	{Name: "version", Description: "Print version and build metadata"},
	{Name: "path", Description: "Print the config directory"},
	{Name: "help", Description: "Print help"},
}

var globalCompletionFlags = []string{"--config-dir", "--json", "--dry-run", "--help", "-h", "--version"}

const ampDialModeCompletions = "low medium high ultra"

func (a app) completion(args []string) error {
	if len(args) != 1 {
		return errors.New("usage: amux completion <bash|zsh|fish>")
	}
	switch args[0] {
	case "bash":
		writeBashCompletion(a.stdout)
	case "zsh":
		writeZshCompletion(a.stdout)
	case "fish":
		writeFishCompletion(a.stdout)
	default:
		return fmt.Errorf("unsupported shell %q; expected bash, zsh, or fish", args[0])
	}
	return nil
}

func writeBashCompletion(w io.Writer) {
	fmt.Fprintf(w, `# bash completion for amux; generated by amux completion bash
_amux_complete() {
  local cur command
  cur="${COMP_WORDS[COMP_CWORD]}"
  command="${COMP_WORDS[1]}"
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "%s %s" -- "$cur") )
    return 0
  fi
  case "$command" in
    worker)
      if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "%s" -- "$cur") )
      else
        COMPREPLY=( $(compgen -W "%s" -- "$cur") )
      fi
      ;;
    spawn) COMPREPLY=( $(compgen -W "--workspace --window --workdir --mode -m --message --message-file --message-stdin --idempotency-key" -- "$cur") ) ;;
    shelve|unshelve|teardown) COMPREPLY=( $(compgen -W "--workspace --thread --current --all" -- "$cur") ) ;;
    completion) COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;
  esac
}
complete -F _amux_complete amux
`, strings.Join(commandNames(completionCommands), " "), strings.Join(globalCompletionFlags, " "), strings.Join(commandNames(completionCommands[0].Subcommands), " "), strings.Join(workerCompletionFlags(), " "))
}

func writeZshCompletion(w io.Writer) {
	fmt.Fprintln(w, "#compdef amux")
	fmt.Fprintln(w, "# zsh completion for amux; generated by amux completion zsh")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "local -a commands")
	fmt.Fprintln(w, "commands=(")
	for _, command := range completionCommands {
		fmt.Fprintf(w, "  %q\n", command.Name+":"+command.Description)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "local -a worker_commands")
	fmt.Fprintln(w, "worker_commands=(")
	for _, command := range completionCommands[0].Subcommands {
		fmt.Fprintf(w, "  %q\n", command.Name+":"+command.Description)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w)
	fmt.Fprintln(w, `_arguments -C \
  '--config-dir[path to config directory]:directory:_directories' \
  '--json[emit exactly one JSON result document]' \
  '--dry-run[print intended actions without mutating]' \
  '--help[print help]' \
  '-h[print help]' \
  '--version[print version]' \
  '1:command:->command' \
  '*::arg:->args'

case $state in
  command)
    _describe -t commands 'amux command' commands
    ;;
  args)
    case $words[2] in
      worker)
        if (( CURRENT == 3 )); then
          _describe -t worker-commands 'worker command' worker_commands
        else
          _arguments '--workspace[workspace]:workspace:' '--window[window]:window:' '--workdir[working directory]:directory:_directories' '--thread[thread id or URL]:thread:' '--shelf[shelf intent]:intent:(shelved unshelved)' '--mode[thread mode]:mode:(low medium high ultra)' '-m[thread mode]:mode:(low medium high ultra)' '--message[initial message]:message:' '--message-file[read initial message from file]:message file:_files' '--message-stdin[read initial message from stdin]' '--idempotency-key[operation key]:key:' '--current[current worker]' '--all[all workers]'
        fi
        ;;
      shelve)
        _arguments '--thread[select by thread id or URL]:thread:' '--workspace[select workspace]:workspace:' '--current[current worker]' '--all[all workers]'
        ;;
      unshelve)
        _arguments '--thread[select by thread id or URL]:thread:' '--workspace[select workspace]:workspace:' '--current[current worker]' '--all[all workers]'
        ;;
      spawn)
        _arguments '--workspace[workspace]:workspace:' '--window[window]:window:' '--workdir[working directory]:directory:_directories' '--mode[thread mode]:mode:(low medium high ultra)' '-m[thread mode]:mode:(low medium high ultra)' '--message[initial message]:message:' '--message-file[read initial message from file]:message file:_files' '--message-stdin[read initial message from stdin]' '--idempotency-key[operation key]:key:'
        ;;
      teardown)
        _arguments '--thread[select by thread id or URL]:thread:' '--workspace[select workspace]:workspace:' '--current[current worker]' '--all[all workers]'
        ;;
      completion)
        _values 'shell' bash zsh fish
        ;;
    esac
    ;;
esac`)
}

func writeFishCompletion(w io.Writer) {
	fmt.Fprintln(w, "# fish completion for amux; generated by amux completion fish")
	for _, flag := range globalCompletionFlags {
		writeFishFlag(w, "__fish_use_subcommand", flag, flagDescription(flag), flagTakesValue(flag))
	}
	for _, command := range completionCommands {
		fmt.Fprintf(w, "complete -c amux -f -n '__fish_use_subcommand' -a %s -d %s\n", fishQuote(command.Name), fishQuote(command.Description))
	}
	for _, command := range completionCommands {
		condition := fmt.Sprintf("__fish_seen_subcommand_from %s", command.Name)
		for _, flag := range command.Flags {
			writeFishFlag(w, condition, flag, flagDescription(flag), flagTakesValue(flag))
		}
		if command.Name == "worker" {
			for _, subcommand := range command.Subcommands {
				fmt.Fprintf(w, "complete -c amux -f -n '__fish_seen_subcommand_from worker; and not __fish_seen_subcommand_from %s' -a %s -d %s\n", strings.Join(commandNames(command.Subcommands), " "), fishQuote(subcommand.Name), fishQuote(subcommand.Description))
				condition := fmt.Sprintf("__fish_seen_subcommand_from worker; and __fish_seen_subcommand_from %s", subcommand.Name)
				for _, flag := range subcommand.Flags {
					writeFishFlag(w, condition, flag, flagDescription(flag), flagTakesValue(flag))
				}
			}
		}
		if command.Name == "completion" {
			fmt.Fprintln(w, "complete -c amux -f -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'")
		}
	}
}

func writeFishFlag(w io.Writer, condition, flag, description string, takesValue bool) {
	short, long := fishFlagNames(flag)
	parts := []string{"complete", "-c", "amux", "-n", fishQuote(condition)}
	if takesValue {
		parts = append(parts, "-r")
	} else {
		parts = append(parts, "-f")
	}
	if flag == "--mode" || flag == "-m" {
		parts = append(parts, "-f", "-a", fishQuote(ampDialModeCompletions))
	}
	if short != "" {
		parts = append(parts, "-s", fishQuote(short))
	}
	if long != "" {
		parts = append(parts, "-l", fishQuote(long))
	}
	parts = append(parts, "-d", fishQuote(description))
	fmt.Fprintln(w, strings.Join(parts, " "))
}

func commandNames(commands []completionCommand) []string {
	names := make([]string, 0, len(commands))
	for _, command := range commands {
		names = append(names, command.Name)
	}
	return names
}

func workerCompletionFlags() []string {
	seen := make(map[string]bool)
	var flags []string
	for _, command := range completionCommands[0].Subcommands {
		for _, flag := range command.Flags {
			if !seen[flag] {
				seen[flag] = true
				flags = append(flags, flag)
			}
		}
	}
	return flags
}

func runnerCompletionCommands() []completionCommand {
	for _, command := range completionCommands {
		if command.Name == "runner" {
			return command.Subcommands
		}
	}
	return nil
}

func flagDescription(flag string) string {
	switch flag {
	case "--config-dir":
		return "Path to config directory"
	case "--json":
		return "Emit one JSON result document"
	case "--dry-run":
		return "Print intended actions without mutating"
	case "--attach":
		return "Always attach after launch"
	case "--no-attach":
		return "Never attach after launch"
	case "--terminal-launcher":
		return "Terminal launcher command"
	case "--status":
		return "Append thread status"
	case "--active":
		return "Only confirmed active rows"
	case "--shelved":
		return "Only confirmed shelved rows"
	case "--thread":
		return "Select by thread id or URL"
	case "--workspace":
		return "Select workspace rows"
	case "--window":
		return "Select worker window"
	case "--workdir":
		return "Select working directory"
	case "--shelf":
		return "Filter shelf intent"
	case "--session":
		return "Tmux session"
	case "--mode", "-m":
		return "Amp thread mode"
	case "--title-prefix":
		return "Window and thread title prefix"
	case "--message-file":
		return "Read initial message from file"
	case "--message":
		return "Initial worker message"
	case "--message-stdin":
		return "Read initial message from stdin"
	case "--idempotency-key":
		return "Stable spawn operation key"
	case "--include-runners":
		return "Include runner-only workspaces"
	case "--help", "-h":
		return "Print help"
	case "--version":
		return "Print version"
	default:
		return flag
	}
}

func flagTakesValue(flag string) bool {
	switch flag {
	case "--config-dir", "--thread", "--workspace", "--window", "--workdir", "--shelf", "--mode", "-m", "--message", "--message-file", "--idempotency-key":
		return true
	default:
		return false
	}
}

func fishFlagNames(flag string) (short, long string) {
	if strings.HasPrefix(flag, "--") {
		return "", strings.TrimPrefix(flag, "--")
	}
	if strings.HasPrefix(flag, "-") {
		return strings.TrimPrefix(flag, "-"), ""
	}
	return "", flag
}

func fishQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
